## DDNS
# Enables or disables the Cloudflare DDNS container // default: "no"
cloudflare_ddns_enabled: no

# The domain that will be used for the Cloudflare DDNS container // default: "{{ hms_docker_domain }}"
cloudflare_ddns_domain: "{{ hms_docker_domain }}"

# The A (or AAAA) record to be created // default: "overseerr"
# May cause issues if not set to "overseerr" due to the Traefik Host rules
cloudflare_ddns_subdomain: overseerr

# Whether to proxy the above record through Cloudflare // default: "true"
cloudflare_ddns_proxied: "true"

# Deletes the record when the container is stopped // default: "false"
cloudflare_ddns_delete_record_on_stop: "false"

# Creates an AAAA record for IPv6 // default: "no"
cloudflare_ddns_create_ipv6_aaaa_record: no
